FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

# Copia os arquivos de publicação do projeto
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

# Configuração final da imagem
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
CMD ["dotnet", "SeuProjeto.dll"]
